name: Backend Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Linting:
    runs-on: ubuntu-latest
    environment: Development Environment

    steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      working-directory: starter/backend
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Run Lint
      working-directory: starter/backend
      run: pipenv run lint

  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      working-directory: starter/backend
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install flake8

    - name: Run Tests
      working-directory: starter/backend
      run: |
        pipenv install pytest
        pipenv run test

  Build:
    needs: [Linting, Test]
    runs-on: ubuntu-latest

    steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIAZJDG7U3FZ4ZO43UT
        aws-secret-access-key: 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
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      working-directory: starter/backend
      env:
        IMAGE_TAG: latest
        REPO_NAME: backend
      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag 638018627275.dkr.ecr.us-east-1.amazonaws.com/backend:latest .
        docker push 638018627275.dkr.ecr.us-east-1.amazonaws.com/backend:latest

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --name cluster --region us-east-1

    - name: Deploy Docker Image to Amazon EKS
      working-directory: starter/backend/k8s
      env:
        IMAGE_TAG: latest
        REPO_NAME: backend
      run: |
        kustomize edit set image backend=638018627275.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        kustomize build | kubectl apply -f -

    - name: Get Kubernetes Services -1
      run: kubectl get svc -A

    - name: Get Kubernetes Services -2
      run: kubectl get pods -A
