name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger of the pipeline

jobs:
  # Lint Job
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the required Node.js version

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint  # Lint the project

  # Test Job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test  # Run the tests

  # Build and Push to ECR Job
  build_and_deploy:
    needs: [lint, test]  # Ensure this runs only after lint and test jobs pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build the application with Docker
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=${{ secrets.REACT_APP_MOVIE_API_URL }} \
            -t frontend:latest .

      - name: Log into Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: AKIAZJDG7U3FZ4ZO43UT
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Push Docker image to ECR
        run: |
          docker tag frontend:latest 638018627275.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          docker push 638018627275.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

      - name: Deploy to EKS using kubectl
        run: |
          aws eks --region us-east-1 update-kubeconfig --name cluster
          kubectl apply -f k8s/deployment.yaml  # Adjust path to your Kubernetes deployment file
          kubectl rollout status deployment/frontend-deployment  # Ensure the deployment completes successfully

